### ISSUE TITLE
fix: `protoc` error when using dev container

### ISSUE THREAD

**Issue by kariy** [dojoengine/dojo#353]
When opening the project on dev container:

```console
error: failed to run custom build command for `apibara-core v0.1.0 (https://github.com/apibara/dna?rev=2c452070372e80e5d1a5302c1b8ae5defef7e9a4#2c452070)`

Caused by:
  process didn't exit successfully: `/workspaces/dojo/target/debug/build/apibara-core-277f36857e4c281b/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=proto/node/v1alpha2/stream.proto
  cargo:rerun-if-changed=proto/node

  --- stderr
  Error: Custom { kind: Other, error: "protoc failed: v1alpha2/stream.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.\n" }
```

`protobuf-compiler` installed using `apt` [here](https://github.com/dojoengine/dojo/blob/0bc0da426fa33015bdcd23c352e9998bbcbeb73e/.devcontainer/Dockerfile#L9) is of version `3.12.4`. Need to install version >= [v3.15.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0).

**Comment by ponderingdemocritus** [comment]
this was fixed upstream on apibara and shouldn't be happening anymore

**Comment by kariy** [comment]
Hmmm but im still getting the error when opening it on dev container.
